### ISSUE TITLE
Support ingesting relations

### ISSUE THREAD

**Issue by okdistribute** [peermaps/ingest#5]
- [x] denormalize relations
- [ ] Add more tests for reading and writing large relations
- [ ] Write relations into the database (depends upon https://github.com/peermaps/georender-pack.rs/issues/6)
- [x] Members with type and role https://github.com/peermaps/georender-pack.rs/issues/9
- [x] Deps with type https://github.com/peermaps/georender-pack.rs/issues/10

**Comment by substack** [comment]
This is working well now.
